credentials:
  usernames:
    admin:
      email: admin@payrollstudio.com
      name: Administrator
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW
cookie:
  expiry_days: 30
  key: random_signature_key_here
  name: payroll_studio_auth
preauthorized:
  emails:
    - admin@payrollstudio.com