COOKIE_NAME = "payroll_studio_cookie"
COOKIE_KEY = "your_secure_random_signature_key_here"
COOKIE_EXPIRY_DAYS = 30

[credentials.usernames.edwardcnn30]
email = "edwardcnn30@example.com"
name = "Mark Edward Cunanan"
password = "$2b$12$PASTE_YOUR_HASH_HERE"